# Generated by Django 3.0.3 on 2020-02-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='movies')),
                ('genre', models.CharField(choices=[('A', 'ACTION'), ('C', 'COMEDY'), ('D', 'DRAMA')], max_length=1)),
                ('lang', models.CharField(choices=[('EN', 'ENGLISH')], max_length=2)),
                ('year', models.DateField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
